### ISSUE TITLE
Error when unicode character with add_image

### ISSUE THREAD

**Issue by mth31** [JelteF/PyLaTeX#187]
Hello,
The first code below is working, but the second raises an error.
Of course, both _/home/mth/nounicode.jpg_ and _/home/mth/unicodé.jpg_ exist (and both are the same duplicate picture).

```Python
#!/usr/bin/env python
# coding: utf-8

from pylatex import Document, Figure

doc = Document()

with doc.create(Figure(position='h!')) as kitten_pic:
    kitten_pic.add_image('/home/mth/nounicode.jpg')     # No problem with this name

doc.generate_pdf('toto', clean_tex=False)
```

```Python
#!/usr/bin/env python
# coding: utf-8

from pylatex import Document, Figure

doc = Document()

with doc.create(Figure(position='h!')) as kitten_pic:
    kitten_pic.add_image('/home/mth/unicodé.jpg')        # The name with é raises an error

doc.generate_pdf('toto', clean_tex=False)
```

```
>>> 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pylatex/document.py", line 228, in generate_pdf
    stderr=subprocess.STDOUT)
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['latexmk', '--pdf', '--interaction=nonstopmode', 'toto.tex']' returned non-zero exit status 12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mth/Pb accents.py", line 11, in <module>
    doc.generate_pdf('toto', clean_tex=False)
  File "/usr/local/lib/python3.4/dist-packages/pylatex/document.py", line 239, in generate_pdf
    print(e.output.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 3116: invalid continuation byte
```
In the log file, I find this :
```
LaTeX Warning: File `/home/mth/unicod\IeC {\'e}.jpg' not found on input lin
e 17.


! Package pdftex.def Error: File `/home/mth/unicod\E9.jpg' not found.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.17 ...0.8\textwidth]{/home/mth/unicodé.jpg}
                                                  %
Using draft setting for this image.
```
Would you have a clue to how I could manage this kind of situation ?
By the way, thank you for your work !

**Comment by JelteF** [comment]
Hmm, this seems like latex not liking unicode again. The best way to debug for me has been to use the `generate_tex` method of `Document` and trying to make it work with plain latex (most of the time with help of google and stackoverflow). If you find a solution you can make a patch for pylatex to apply that automatically.

**Comment by mth31** [comment]
You are right, the problem is coming from latex, specifically from \includegraphics I would say (see first post for the error).
Google didn't give me any idea yet, but if find a solution I will come back here.
For now, I will try to avoid "unicode" characters in the names and path of the pictures (yes, I know it's bad anyway)...
Thank you again.

**Comment by JelteF** [comment]
Alright if avoiding is possible it's indeed probably easiest, but maybe this helps: https://tex.stackexchange.com/a/213568

**Comment by mth31** [comment]
It's working, thank you very much !
I thought I tried that already, but I didn't do it correctly somehow...
So this works (in Python) :
```Python
doc.packages.add(Package('grffile', options=['encoding', 'filenameencoding=utf8']))
```

Entire example code :
```Python
#!/usr/bin/env python
# coding: utf-8

from pylatex import Document, Figure, Package         # Package needed

doc = Document()
# This line needed :
doc.packages.add(Package('grffile', options=['encoding', 'filenameencoding=utf8']))

with doc.create(Figure(position='h!')) as kitten_pic:
    kitten_pic.add_image('/home/mth/unicodé.jpg')

doc.generate_pdf('toto', clean_tex = False)
```

To be complete, my problem appeared when I tried the [full example](https://jeltef.github.io/PyLaTeX/latest/examples/full.html) : the path was not correct with
```Python
image_filename = os.path.join(os.path.dirname(__file__), 'kitten.jpg')
```
Now it's correct :
```Python
if __name__ == '__main__':

    geometry_options = {"tmargin": "1cm", "lmargin": "10cm"}
    doc = Document(geometry_options=geometry_options)
    doc.packages.add(Package('grffile', options=['encoding', 'filenameencoding=utf8']))
    image_filename = os.path.join(os.path.dirname(__file__), 'kitten.jpg')
```

Thank you again for your work and your suggestions.
Mth

**Comment by JelteF** [comment]
Good to hear that you found a solution. It would be nice if you could
create a pull request to solve this in pylatex. I think the best would be
to check the path in add_image and see if it contains non ascci characters.
If that's the case than you can add it to the packages list of the figure.
Then you can include your snippet above as a test in the tests directory.

**Comment by mth31** [comment]
I'm afraid I can't do that. I have no idea how to create a pull request, and I am an amateur in python.
However I watched in the code, and I would suggest to add this lines in the `class StandAloneGraphic` from figure.py, first in the `def __init__` function :
```Python
if not all(ord(char) < 128 for char in filename):
    packages.add(Package('grffile', options=['encoding', 'filenameencoding=utf8']))
```
But I'm not sure if `packages.add` will work (in my case, I was using `doc.packages.add` instead).

Also, what if someone doesn't use utf8 as encoding but something else ? (might be rare though).

I'm afraid that's all I can do myself.
Thank you very much, sorry I can't help more.

**Comment by JelteF** [comment]
No problem. Thanks for the info. I'll leave the issue open for now and will maybe fix it myself using your snippets in the future when I have some time.
