### ISSUE TITLE
Issue with pdflatex missing

### ISSUE THREAD

**Issue by tklightningfast** [JelteF/PyLaTeX#194]
Hello, I'm new to python but I want to use pylatex. So far, I've installed correctly and can import fine, but every time I try to generate the pdf, `doc.generate_pdf`, the following error is thrown:
` Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Tanishq/.virtualenvs/discord/lib/python3.6/site-packages/pylatex/document.py", line 274, in generate_pdf
    raise(os_error)
  File "/Users/Tanishq/.virtualenvs/discord/lib/python3.6/site-packages/pylatex/document.py", line 228, in generate_pdf
    stderr=subprocess.STDOUT)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'pdflatex' `

How can I fix this? i'm using Mac. And I'm installing latex through a virtualenv called discord.

**Comment by JelteF** [comment]
Make sure pdflatex/texlive (and maybe latexmk) is installed and in your
PATH.
