### ISSUE TITLE
Few of the examples does't work with Python2

### ISSUE THREAD

**Issue by hygull** [JelteF/PyLaTeX#212]
Today, I tried to run example 2 i.e. `basic_inheritance.py` and it did not run.

I think PyLaTeX's provided works fine with Python3 only and it does not work well with Python2.

Below is a paste of part of my Windows Teminal.

```python
(pylatex) E:\RishikeshAgrawani\projects\Python3\PyLaTeX\pylatex\02_basic_inheritance>python basic_inheritance.py
Traceback (most recent call last):
  File "basic_inheritance.py", line 27, in <module>
    doc = MyDocument()
  File "basic_inheritance.py", line 7, in __init__
    super().__init__(self)
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by JelteF** [comment]
Yeah, that makes sense. It should probably be noted that the examples are
all python 3.
