### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'argument', in "pylatex/numpy.py", line 20

### ISSUE THREAD

**Issue by Vayel** [JelteF/PyLaTeX#22]
Hi!

When using the `VectorName` class, I got that error: 

```
Traceback (most recent call last):
  File "latex.py", line 56, in <module>
    latex.save("./test")
  File "latex.py", line 35, in save
    self.draw()
  File "latex.py", line 28, in draw
    k, v = self.parse(k, v)
  File "latex.py", line 20, in parse
    return VectorName("wsd"), Matrix(v)
  File "/home/vincent/.local/share/virtualenvs/mpf/lib/python3.4/site-packages/pylatex/numpy.py", line 20, in __init__
    super().__init__('mathbf', argument=name)
TypeError: __init__() got an unexpected keyword argument 'argument'
```

Yet, the [code](https://github.com/JelteF/PyLaTeX/blob/master/pylatex/numpy.py#L20) on GitHub is correct. Is the version on Pypi up-to-date? 

Thanks!

**Comment by JelteF** [comment]
I fixed that code last night and have just pushed an update to Pypi that fixes this issue.
