### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 15294: invalid continuation byte

### ISSUE THREAD

**Issue by nvillegase** [JelteF/PyLaTeX#251]
Hello. I'm using pyLaTeX along with 'pdflatex' compiler to compile a .tex file. Although the .pdf file is generated, I'm always getting this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pylatex/document.py", line 233, in generate_pdf
    stderr=subprocess.STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pdflatex', '--interaction=nonstopmode', 'prueba.tex']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prueba.py", line 39, in <module>
    doc.generate_pdf('../assets/pdf/prueba', clean_tex=False, compiler='pdflatex')
  File "/usr/local/lib/python3.6/dist-packages/pylatex/document.py", line 244, in generate_pdf
    print(e.output.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 15294: invalid continuation byte
```
After the error raises, the 'auxiliary' files don't get removed (clean set to True). I've tried to use a different encoding ('latin-1'), and have tried to use different compilers but cannot get past it. 
Not sure if relevant, but the texts inside my .tex file are written in spanish.
Thanks for your attention!

**Comment by teodorwisniewski** [comment]
Hi there,
I a have similar program during the compilation of "generate_pdf" function:
"'utf-8' codec can't decode byte 0xe9 in position 26306: invalid continuation byte."

I have a quick fix to it:
    try:
        doc.generate_pdf(nom_output,compiler='pdflatex') 
    except Exception as e:
        print(e)
It generates a pdf file and other related files to tex file generation, but the exception is still raised.

**Comment by JelteF** [comment]
It's impossible to help with this without an reproducible example.

**Comment by daviddavo** [comment]
I have the same problem.
In my case, I think it happens with `t.add_row("ID", "Nombre", "Edad", "Teléfono", "Horas", "Comentario", mapper=utils.bold)` because it fails to decode byte 0xe9 (é)

```
Traceback (most recent call last):
  File "/home/davo/.local/lib/python3.8/site-packages/pylatex/document.py", line 232, in generate_pdf
    output = subprocess.check_output(command,
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pdflatex', '--interaction=nonstopmode', 'completo.tex']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./cosoMEL.py", line 110, in <module>
    genDocument(d)
  File "./cosoMEL.py", line 105, in genDocument
    doc.generate_pdf("build/completo", compiler="pdflatex", clean=False, clean_tex=False)
  File "/home/davo/.local/lib/python3.8/site-packages/pylatex/document.py", line 244, in generate_pdf
    print(e.output.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 4173: invalid continuation byte
```

**Comment by kimond** [comment]
I got the same issue but I think I know the solution.


It comes from https://github.com/JelteF/PyLaTeX/blob/master/pylatex/document.py#L256

```python
            except subprocess.CalledProcessError as e:
                # For all other errors print the output and raise the error
                print(e.output.decode())
                raise
            else:
                if not silent:
                    print(output.decode())
```

I think we don't need to use `.decode()` anymore.
