### ISSUE TITLE
Example code not running

### ISSUE THREAD

**Issue by srinivasaravind5** [JelteF/PyLaTeX#260]
Traceback (most recent call last):
  File "payment_receipt.py", line 24, in <module>
    doc.generate_pdf(clean_tex=False)
  File "/home/aravind/profile_api_receipt/lib/python3.6/site-packages/pylatex/document.py", line 281, in generate_pdf
    'or make sure you have latexmk or pdfLaTex installed.'
pylatex.errors.CompilerError: No LaTex compiler was found
Either specify a LaTex compiler or make sure you have latexmk or pdfLaTex installed.

**Comment by srinivasaravind5** [comment]
```
from pylatex import Document, Section, Subsection, Command
from pylatex.utils import italic, NoEscape


def fill_document(doc):
    """Add a section, a subsection and some text to the document.

    :param doc: the document
    :type doc: :class:`pylatex.document.Document` instance
    """
    with doc.create(Section('A section')):
        doc.append('Some regular text and some ')
        doc.append(italic('italic text. '))

        with doc.create(Subsection('A subsection')):
            doc.append('Also some crazy characters: $&#{}')


if __name__ == '__main__':
    # Basic document
    doc = Document('basic')
    fill_document(doc)

    doc.generate_pdf(clean_tex=False)
    doc.generate_tex()

    # Document with `\maketitle` command activated
    doc = Document()

    doc.preamble.append(Command('title', 'Awesome Title'))
    doc.preamble.append(Command('author', 'Anonymous author'))
    doc.preamble.append(Command('date', NoEscape(r'\today')))
    doc.append(NoEscape(r'\maketitle'))

    fill_document(doc)

    doc.generate_pdf('basic_maketitle', clean_tex=False)

    # Add stuff to the document
    with doc.create(Section('A second section')):
        doc.append('Some text.')

    doc.generate_pdf('basic_maketitle2', clean_tex=False)
    tex = doc.dumps()  # The document as string in LaTeX syntax

```

**Comment by JelteF** [comment]
Seems like a pretty clear error to me, you have to install latexmk or pdfLatex

**Comment by srinivasaravind5** [comment]
Why is it not part of the documentation and steps to install?
